const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const dom=new JSDOM('<div id="app"></div>',{runScripts:'outside-only',url:'https://eburum.vercel.app'}),w=dom.window,run=code=>vm.runInContext(code,dom.getInternalVMContext());
w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;w.CONFIG={supabaseUrl:'demo',supabaseAnonKey:'demo',season:'2026/27'};w.scrollTo=()=>{};
run(fs.readFileSync(__dirname+'/fixtures/team-ui.js','utf8'));
const ready=require('./load-app.cjs').loadApp(dom);
(async()=>{await ready;
run("state.user=fixtureUser");await run('refresh()');run("state.team.role='secretary';state.page='dashboard';render()");
const $=s=>w.document.querySelector(s);
assert.ok($('[data-expiries]'));assert.equal($('#users'),null);assert.equal($('[data-page="training"]'),null);
$('[data-expiries]').click();assert.match($('#expiryTitle').textContent,/Scadenze/);$('.modal-head button').click();
run("state.page='more';render()");assert.match($('#app').textContent,/Segretario/);assert.equal($('#teamUsers'),null);assert.ok($('[data-expiries]'));
run("playerSheet('player-1')");assert.ok($('#playerAdminForm'));$('.modal-head button').click();
run("state.page='matches';render()");assert.equal($('#addMatch'),null);$('[data-match]').click();assert.ok($('#readonlyActivityTitle'));assert.equal($('#activityForm'),null);assert.equal($('#technicalNote'),null);assert.match($('.modal').textContent,/Consultazione/);$('.modal-head button').click();
run("state.page='agenda';render()");assert.equal($('[data-new-activity]'),null);
run("state.page='training';render()");assert.equal(run('state.page'),'register');assert.equal($('#saveTraining'),null);
run("state.page='reports';render()");assert.ok($('#exportReportPdf'));
run("state.team.role='admin';usersModal()");assert.ok($('#newUserRole option[value="secretary"]'));$('#newUserRole').value='secretary';$('#newUserRole').dispatchEvent(new w.Event('change'));assert.match($('#roleHelp').textContent,/scadenze/);assert.match($('#roleHelp').textContent,/nessuna modifica/);
const tick=()=>new Promise(resolve=>setTimeout(resolve,20));await tick();
let requests=[],release;
w.invoke=async(name,{body})=>{requests.push(body);if(body.action==='list')return {data:{users:[{id:'demo-user',email:'owner@example.test',role:'admin'}]}};return await new Promise(resolve=>{release=resolve})};run('db.functions.invoke=window.invoke');
const form=$('#createUserForm'),submit=()=>form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
$('#newUserEmail').value='coach@example.test';$('#newUserPassword').value='synthetic-password-123';$('#newUserRole').value='coach';submit();submit();
assert.equal(requests.filter(r=>r.action==='create').length,1);assert.ok($('#newUserEmail').disabled);assert.ok($('#newUserRole').disabled);
release({error:{context:{clone:()=>({json:async()=>({error:'Email gia registrata'})})}}});await tick();
assert.match($('#userMessage').textContent,/gia registrata/);assert.equal($('#newUserEmail').value,'coach@example.test');assert.equal($('#newUserPassword').value,'synthetic-password-123');assert.equal($('#newUserRole').value,'coach');assert.equal($('#newUserEmail').disabled,false);
$('#newUserEmail').value='new-coach@example.test';submit();release({data:{user:{id:'synthetic-created'}}});await tick();
assert.match($('#userMessage').textContent,/creata e associata/);assert.equal($('#newUserEmail').value,'');assert.equal($('#newUserPassword').value,'');assert.equal($('#newUserEmail').disabled,false);assert.equal(requests.filter(r=>r.action==='create').length,2);

dom.window.close();console.log('PASS: secretary dashboard expiries, administrative editor, read-only matches, hidden sporting commands, reports and admin role selection, single creation submit, field locking, explicit errors, retry retention and success cleanup');
})().catch(error=>{console.error(error);process.exitCode=1;dom.window.close()});
