const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
let handler,created,changed,changeError;const members=[{user_id:'owner',owner_id:'owner',role:'admin',display_name:'owner@example.test'},{user_id:'coach',owner_id:'owner',role:'coach',display_name:'coach@example.test'},{user_id:'second-admin',owner_id:'owner',role:'admin',display_name:'staff@example.test'},{user_id:'other',owner_id:'other',role:'admin',display_name:'other@example.test'}];
class Query{constructor(){this.filters=[]}select(){return this}eq(k,v){this.filters.push(r=>r[k]===v);return this}single(){this.one=true;return this}order(){return this}range(a,b){this.bounds=[a,b];return this}update(row){this.row=row;return this}then(resolve){let rows=members.filter(r=>this.filters.every(f=>f(r)));if(this.row)rows.forEach(r=>Object.assign(r,this.row));if(this.bounds)rows=rows.slice(this.bounds[0],this.bounds[1]+1);return Promise.resolve({data:this.one?rows[0]:rows,error:null}).then(resolve)}}
const client={from:()=>new Query(),auth:{getUser:async token=>({data:{user:members.some(r=>r.user_id===token)?{id:token,app_metadata:{role:token==='coach'?'admin':'member'}}:null},error:null}),admin:{updateUserById:async(id,body)=>{changed={id,body};return {data:{user:{id}},error:changeError}},createUser:async body=>{created=body;return {data:{user:{id:'new',email:body.email}},error:null}}}}};
let source=fs.readFileSync(__dirname+'/../supabase/functions/manage-users/index.ts','utf8').replace(/^import.*\r?\n/,'').replace('req: Request','req').replace('status: number','status').replace('body: unknown','body').replace('Deno.env.get("SUPABASE_URL")!','Deno.env.get("SUPABASE_URL")').replace('serverKey!','serverKey');vm.runInNewContext(source,{Deno:{serve:fn=>handler=fn,env:{get:()=>undefined}},createClient:()=>client,Response,Request,Set,JSON,Number});
const call=async(token,body)=>{const response=await handler(new Request('https://example.test',{method:'POST',headers:{...(token?{Authorization:'Bearer '+token}:{}),'Content-Type':'application/json'},body:JSON.stringify(body)}));return {status:response.status,data:await response.json()}};
(async()=>{assert.equal((await call(null,{action:'list'})).status,401);assert.equal((await call('forged',{action:'list'})).status,401);assert.equal((await call('coach',{action:'list'})).status,403,'stale admin metadata does not grant admin');const list=await call('second-admin',{action:'list'});assert.equal(list.status,200,'membership grants admin even with member metadata');assert.equal(list.data.users.length,3);assert.equal(list.data.users.some(u=>u.id==='other'),false);assert.equal((await call('other',{action:'role',userId:'coach',role:'admin'})).status,404);assert.equal((await call('owner',{action:'role',userId:'owner',role:'manager'})).status,400);assert.equal((await call('owner',{action:'create',email:'new@example.test',password:'synthetic-password-123',role:'coach'})).status,201);assert.equal(created.app_metadata.team_role,'coach');assert.equal(created.app_metadata.created_by,'owner');assert.equal(created.app_metadata.managed_account,true);for(const token of ['coach',null,'forged']){assert.ok([401,403].includes((await call(token,{action:'password',userId:'second-admin',password:'synthetic-password-123'})).status));assert.ok([401,403].includes((await call(token,{action:'create',email:'test@example.test',password:'synthetic-password-123'})).status))}
assert.equal(changed,undefined);
assert.equal((await call('owner',{action:'password',userId:'other',password:'synthetic-password-123'})).status,404);
assert.equal((await call('owner',{action:'password',userId:'owner',password:'synthetic-password-123'})).status,400);
assert.equal((await call('owner',{action:'password',userId:'coach',password:'short'})).status,400);
assert.equal(changed,undefined);
const updated=await call('owner',{action:'password',userId:'coach',password:'synthetic-password-123',role:'admin'});assert.equal(updated.status,200);assert.equal(JSON.stringify(updated.data).includes('password'),false);assert.equal(changed.id,'coach');assert.deepEqual(Object.keys(changed.body),['password']);assert.equal(members.find(r=>r.user_id==='coach').role,'coach');
changeError={message:'sensitive backend error'};const failed=await call('owner',{action:'password',userId:'coach',password:'synthetic-password-123'});assert.equal(failed.status,400);assert.equal(JSON.stringify(failed.data).includes('sensitive'),false);changeError=null;
assert.equal((await call('owner',{action:'create',email:'test@example.test',password:'synthetic-password-123',role:'invalid'})).status,400);assert.equal((await call('owner',{action:'role',userId:'coach',role:'secretary'})).status,200);for(const action of ['list','create','role','password'])assert.equal((await call('coach',{action,userId:'second-admin',role:'admin',email:'test@example.test',password:'synthetic-password-123'})).status,403);assert.equal((await call('owner',{action:'create',email:'secretary@example.test',password:'synthetic-password-123',role:'secretary'})).status,201);assert.equal(created.app_metadata.team_role,'secretary');
assert.equal((await call('owner',{action:'role',userId:'coach',role:'manager'})).status,200);assert.equal(members.find(r=>r.user_id==='coach').role,'manager');assert.equal((await call('coach',{action:'password',userId:'second-admin',password:'synthetic-password-123'})).status,403,'manager denied after role change');console.log('PASS: staff handler auth, authoritative roles, scoped lists, cross-team denial, owner protection, account metadata and role updates')})().catch(e=>{console.error(e);process.exitCode=1});
