const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const dom=new JSDOM('<div id="app"></div>',{runScripts:'outside-only',url:'https://eburum.vercel.app',beforeParse(w){const Base=w.Date;w.Date=class extends Base{constructor(...args){super(...(args.length?args:['2026-10-08T12:00:00+02:00']))}static now(){return new Base('2026-10-08T12:00:00+02:00').getTime()}}}}),w=dom.window,run=code=>vm.runInContext(code,dom.getInternalVMContext());w.CONFIG={supabaseUrl:'demo',supabaseAnonKey:'demo',season:'2026/27'};w.scrollTo=()=>{};
run(fs.readFileSync(__dirname+'/fixtures/team-ui.js','utf8'));for(const file of ['app-dialogs.js','app-part1.js','app-part2.js','app-part3.js','app-part4.js','app-report-export.js','app-part5.js','app-team.js','app-operations.js','app-workflows.js','app-access.js','app-discipline.js','app-communications.js','app-admin.js'])run(fs.readFileSync(__dirname+'/../'+file,'utf8').replace(/boot\(\);\s*$/,''));
const $=s=>w.document.querySelector(s),all=s=>[...w.document.querySelectorAll(s)],tick=()=>new Promise(r=>setTimeout(r,30)),input=(s,v)=>{$(s).value=v;$(s).dispatchEvent(new w.Event('input',{bubbles:true}))},submit=s=>$(s).dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
(async()=>{
run('state.user=fixtureUser');await run('refresh()');let copied='';Object.defineProperty(w.navigator,'clipboard',{value:{writeText:async text=>copied=text}});
run("state.page='training';state.trainingMode='survey';render()");assert.ok($('#surveyActivity'));const actualBefore=w.fixtureData.attendance.length,sessionsBefore=w.fixtureData.sessions.length;$('#newSurvey').click();assert.equal($('[data-activity-panel="roster"]').hidden,false);
$('[data-roster-edit="player-1"]').closest('.roster-person').querySelector('[data-availability="Indisponibile"]').click();assert.match($('#activitySaveState').textContent,/non salvate/);$('[data-roster-filter="pending"]').click();assert.equal(all('.roster-person').filter(el=>!el.hidden).length,1);$('#copyActivityReminder').click();await tick();assert.match(copied,/BOZZA/);assert.match(copied,/Bianchi/);assert.doesNotMatch(copied,/Rossi/);submit('#activityForm');await tick();assert.equal(w.fixtureData.attendance.length,actualBefore,'poll must not create attendance');assert.equal(w.fixtureData.sessions.length,sessionsBefore,'poll must not create actual sessions');assert.equal(w.fixtureTeamCalls.at(-1).p_roster.length,2,'filtered full-roster save');assert.equal(w.fixtureTeamCalls.at(-1).p_roster.find(r=>r.player_id==='player-1').availability,'Indisponibile');
const aid=w.fixtureData.activities.at(-1).id;await run(`openActivity('${aid}','roster')`);$('#activityAttendance').click();await tick();assert.equal($('#activityForm'),null);assert.equal(run("trainingDraft.entries.get('player-1').status"),'Presente','predicted absence does not become actual absence');assert.equal(run("trainingDraft.entries.get('player-1').notified"),true);assert.equal(run("trainingDraft.entries.get('player-2').notified"),false);assert.match($('#trainList').textContent,/Disponibilità prévue|Disponibilità prevista/);assert.match($('#trainingFilterSummary').textContent,/Tutti/);
$('[data-a="player-1"]').click();$('[data-status="Assente"]').click();$('#ok').click();await tick();$('#saveTraining').click();assert.match($('#reviewTitle').textContent,/Riepilogo/);assert.match($('.attendance-review').textContent,/presenze effettive/);$('#confirmTraining').click();await tick();assert.equal(w.fixtureRpcCalls.at(-1).p_attendance.find(r=>r.player_id==='player-1').status,'Assente');assert.equal(w.fixtureData.activity_roster.find(r=>r.activity_id===aid&&r.player_id==='player-1').availability,'Indisponibile','planned reply preserved');
run("state.page='training';state.trainingMode='actual';trainingDraft=null;render()");input('#td','2300-01-01');$('#saveTraining').click();assert.equal($('.attendance-review'),null,'future actual attendance rejected');run('trainingDraft=null');
// Date-based match phase, immediate events and protection of unsaved fields.
run("fixtureData.activities[0].activity_date='2020-01-01';state.page='matches';render()");$('[data-match="match-1"]').click();await tick();assert.equal($('[data-activity-panel="results"]').hidden,false,'past match opens after-match results');$('[data-match-phase="during"]').click();$('#quickPhaseEvent').click();assert.ok($('#eventForm'));$('[data-event-type="Nota"]').click();input('#eventDetail','Osservazione test');submit('#eventForm');await tick();assert.match($('#matchEventList').textContent,/Osservazione test/);$('[data-match-phase="before"]').click();input('#activityName','Bozza da conservare');$('[data-match-phase="during"]').click();assert.equal($('#activityName').value,'Bozza da conservare');assert.equal($('[data-activity-panel="results"]').hidden,true,'phase switch cannot bypass dirty guard');$('#closeActivity').click();
// Period-scoped reports, drills and invalid ranges.
run("state.page='reports';render()");$('#rp').value='player-1';$('#rp').dispatchEvent(new w.Event('change'));input('#rf','2026-10-01');$('#rf').dispatchEvent(new w.Event('change'));input('#rt','2026-10-08');$('#rt').dispatchEvent(new w.Event('change'));assert.match($('#reportPeriodLabel').textContent,/01\/10\/2026/);$('[data-report-detail="absent"]').click();assert.match($('#reportDetailTitle').textContent,/Assenze/);assert.match($('.modal').textContent,/Rossi/);$('[data-drill-player="player-1"]').click();assert.equal($('#rp').value,'player-1');assert.equal($('#playerPicker').hidden,false);assert.match($('#playerHistory').textContent,/Assente/);$('#copyReport').click();await tick();assert.match(copied,/Periodo/);assert.match(copied,/Rossi/);input('#rf','2026-11-01');$('#rf').dispatchEvent(new w.Event('change'));assert.equal($('#reportContent').hidden,true);assert.equal($('#copyReport').disabled,true);assert.match($('#reportError').textContent,/periodo valido/);
// Current-month goals cannot include opponents or a cancelled fixture.
run("state.team.role='coach';state.page='dashboard';render()");assert.equal($('[data-expiries]'),null);assert.ok($('[data-priority="poll"]'));$('[data-priority="poll"]').click();assert.match($('#priorityTitle').textContent,/Sondaggi/);$('.modal-head button').click();
console.log('PASS: separate survey persistence, quick replies, pending filter and full reminders, full-roster saves, planned versus actual attendance, future-date guard, automatic match phases, immediate events, dirty guard, period reports, drilldowns, player detail, invalid ranges and role priorities');dom.window.close();
})().catch(error=>{console.error(error);process.exitCode=1;dom.window.close()});
