function reportData(from,to,player=null){
 const sessions=state.sessions.filter(s=>s.session_date>=from&&s.session_date<=to),sessionIds=new Set(sessions.map(s=>s.id)),attendance=state.attendance.filter(r=>sessionIds.has(r.session_id)&&(!player||r.player_id===player));
 const activities=(state.activities||[]).filter(a=>a.activity_date>=from&&a.activity_date<=to&&a.status!=='Annullato'),activityIds=new Set(activities.map(a=>a.id)),roster=(state.roster||[]).filter(r=>activityIds.has(r.activity_id)&&(!player||r.player_id===player));
 const matches=state.matches.filter(m=>m.match_date>=from&&m.match_date<=to&&!(state.activities||[]).some(a=>a.match_id===m.id&&a.status==='Annullato')),matchIds=new Set(matches.map(m=>m.id)),events=state.events.filter(e=>matchIds.has(e.match_id)&&(!player||e.player_id===player||e.outgoing_player_id===player));
 const availability=activities.flatMap(a=>pollEntries(a).filter(x=>!player||x.player.id===player).map(x=>({activity:a,...x})));
 return {from,to,player,sessions,attendance,activities,roster,matches,events,availability};
}
function reportsPage(){
 return `<div class="section-title"><div><h2>Report giocatore</h2><p class="muted">Presenze, disponibilità e impiego nel periodo selezionato.</p></div><div class="report-export-actions"><button id="copyReport">Copia testo</button><button class="primary" id="exportReportPdf">Scarica PDF</button></div></div><section class="card report-filters"><div class="report-presets" role="group" aria-label="Periodo report"><button data-report-period="7">7 giorni</button><button data-report-period="30" aria-pressed="true">30 giorni</button><button data-report-period="month">Questo mese</button><button data-report-period="all">Tutto lo storico</button></div><div class="form-grid field-space report-range-fields"><div class="field"><label for="rf">Dal</label><input id="rf" type="date" value="${recentFrom(30)}"></div><div class="field"><label for="rt">Al</label><input id="rt" type="date" value="${today()}"></div></div><div id="playerPicker" class="field field-space"><label for="rp">Giocatore</label><select id="rp">${sortPlayers(state.players).map(p=>`<option value="${p.id}">${esc(p.surname)} ${esc(p.name)}${p.active?'':' · Inattivo'}</option>`).join('')}</select></div><p id="reportPeriodLabel" class="filter-summary" aria-live="polite"></p><p id="reportError" role="status" aria-live="polite"></p></section><div id="reportContent"><section class="report-section"><h3>Presenze effettive</h3><p class="row-sub">Le disponibilità del sondaggio non sono conteggiate come presenze. Tocca un indicatore per consultarne i dettagli.</p><div id="reportStats" class="player-kpis"></div></section><section class="report-section"><h3>Partite e impiego</h3><div id="sportStats" class="player-kpis"></div></section><section class="report-section"><h3>Andamento delle presenze</h3><div id="attendanceTrend" class="attendance-trend"></div></section><section class="report-section"><h3>Grafici del giocatore</h3><div id="playerCharts" class="player-charts"></div></section><div id="playerHistory" class="player-history"></div><details class="report-text-details"><summary>Testo del report</summary><pre id="report" class="report"></pre></details></div><p id="reportCopyStatus" class="row-sub" role="status"></p>`;
};
function reportDrilldown(title,items,range){
 const root=document.createElement('div');root.className='modal-back';root.innerHTML=`<section class="modal" role="dialog" aria-modal="true" aria-labelledby="reportDetailTitle"><div class="modal-head"><h2 id="reportDetailTitle">${esc(title)}</h2><button aria-label="Chiudi dettagli report">✕</button></div><p class="muted">${fmt(range.from)} – ${fmt(range.to)} · ${items.length} registrazioni</p><div class="list">${items.map(x=>`<article class="row"><div class="row-main"><b>${esc(x.name)}</b><p class="row-sub">${esc(x.detail)}</p></div>${x.player?`<button data-drill-player="${x.player}" aria-label="Report di ${esc(x.name)}">Report</button>`:''}</article>`).join('')||'<p class="empty">Nessuna registrazione nel periodo.</p>'}</div></section>`;document.body.append(root);const close=()=>root.remove();root.querySelector('.modal-head button').onclick=close;bindDialog(root,close);root.querySelectorAll('[data-drill-player]').forEach(b=>b.onclick=()=>{close();document.querySelector('#rp').value=b.dataset.drillPlayer;document.querySelector('#rp').dispatchEvent(new Event('change'))});
}
function bindReports(){
 let mode='player',current=null,drills={};const $=s=>document.querySelector(s),names=new Map(state.players.map(p=>[p.id,`${p.surname} ${p.name}`]));
 const metric=(key,value,label)=>`<button class="report-metric" data-report-detail="${key}" aria-label="${label}: ${value}. Apri dettagli"><b>${value}</b><span>${label}</span><small>Vedi dettagli ›</small></button>`;
 const paint=()=>{
 const from=$('#rf').value,to=$('#rt').value,valid=!!from&&!!to&&from<=to&&!!$('#rp').value;$('#reportError').textContent=valid?'':'Seleziona un giocatore e un periodo valido: la data iniziale deve precedere o coincidere con quella finale.';$('#reportContent').hidden=!valid;$('#copyReport').disabled=!valid;$('#exportReportPdf').disabled=!valid;if(!valid){current=null;$('#reportPeriodLabel').textContent='Periodo non valido';$('#report').textContent='';return}
 const player=mode==='player'?$('#rp').value:null,d=reportData(from,to,player);current=d;const sessionMap=new Map(d.sessions.map(s=>[s.id,s])),activityMap=new Map(d.activities.map(a=>[a.id,a])),matchMap=new Map(d.matches.map(m=>[m.id,m]));
 const present=d.attendance.filter(r=>r.status==='Presente'),absent=d.attendance.filter(r=>r.status==='Assente'),injured=d.attendance.filter(r=>r.status==='Infortunato'),rate=d.attendance.length?Math.round(present.length/d.attendance.length*100):null;
 const called=d.roster.filter(r=>r.called&&activityMap.get(r.activity_id)?.activity_type==='Partita'),minutes=d.roster.filter(r=>r.minutes_played>0&&activityMap.get(r.activity_id)?.activity_type==='Partita'),goals=d.events.filter(e=>e.event_type==='Gol'&&e.player_id),cards=d.events.filter(e=>e.player_id&&['Ammonizione','Espulsione'].includes(e.event_type));
 $('#reportPeriodLabel').textContent=`${fmt(from)} – ${fmt(to)} · ${mode==='player'?(names.get(player)||'Nessun giocatore'):'Squadra'} · ${d.attendance.length} registrazioni di presenza`;
 $('#reportStats').innerHTML=metric('sessions',new Set(d.attendance.map(r=>r.session_id)).size,'Sessioni registrate')+metric('present',present.length,'Presenze')+metric('absent',absent.length,'Assenze')+metric('injured',injured.length,'Infortuni');
 $('#sportStats').innerHTML=metric('called',called.length,'Convocazioni')+metric('minutes',minutes.reduce((n,r)=>n+Number(r.minutes_played||0),0),'Minuti registrati')+metric('goals',goals.length,'Gol dei giocatori')+metric('cards',cards.length,'Cartellini');
 const attendanceItems=rows=>rows.map(r=>({name:names.get(r.player_id)||'Giocatore storico',detail:`${fmt(sessionMap.get(r.session_id)?.session_date)} · ${sessionMap.get(r.session_id)?.session_type||'Sessione'} · ${r.status}${r.note?' · '+r.note:''}`,player:r.player_id}));
 const rosterItems=rows=>rows.map(r=>({name:names.get(r.player_id)||'Giocatore storico',detail:`${fmt(activityMap.get(r.activity_id)?.activity_date)} · ${activityMap.get(r.activity_id)?.title||'Attività'} · ${r.lineup} · ${r.minutes_played} min`,player:r.player_id}));
 const eventItems=rows=>rows.map(e=>({name:e.player_id?names.get(e.player_id)||'Giocatore storico':'Avversario / squadra',detail:`${fmt(matchMap.get(e.match_id)?.match_date)} · ${matchMap.get(e.match_id)?.opponent||'Partita'} · ${e.event_type}${e.minute==null?'':' · '+e.minute+'′'}`,player:e.player_id}));
 drills={sessions:['Sessioni',d.sessions.filter(s=>d.attendance.some(r=>r.session_id===s.id)).map(s=>({name:s.session_type,detail:`${fmt(s.session_date)} · ${d.attendance.filter(r=>r.session_id===s.id).length} registrazioni`}))],present:['Presenze',attendanceItems(present)],absent:['Assenze',attendanceItems(absent)],injured:['Infortuni',attendanceItems(injured)],called:['Convocazioni',rosterItems(called)],minutes:['Minuti giocati',rosterItems(minutes)],goals:['Gol dei giocatori',eventItems(goals)],cards:['Cartellini',eventItems(cards)]};
 $('#reportContent').querySelectorAll('[data-report-detail]').forEach(b=>b.onclick=()=>{const [title,items]=drills[b.dataset.reportDetail];reportDrilldown(title,items,d)});
 const monthGroups=new Map();for(const r of d.attendance){const month=sessionMap.get(r.session_id).session_date.slice(0,7);if(!monthGroups.has(month))monthGroups.set(month,[]);monthGroups.get(month).push(r)}
 $('#attendanceTrend').innerHTML=[...monthGroups].sort(([a],[b])=>a.localeCompare(b)).map(([month,rows])=>{const count=rows.filter(r=>r.status==='Presente').length,pct=Math.round(count/rows.length*100),label=new Intl.DateTimeFormat('it-IT',{month:'short',year:'numeric'}).format(new Date(month+'-15T12:00:00'));return `<div class="trend-row"><span>${esc(label)}</span><meter min="0" max="100" value="${pct}" aria-label="${label}: ${count} presenze su ${rows.length}">${pct}%</meter><b>${pct}%</b><small>${count}/${rows.length} registrazioni</small></div>`}).join('')||'<p class="empty">Nessuna presenza registrata nel periodo selezionato.</p>';
 $('#playerHistory').innerHTML=mode==='player'?`<h3>Storico nel periodo</h3><div class="list">${attendanceItems([...d.attendance].sort((a,b)=>sessionMap.get(b.session_id).session_date.localeCompare(sessionMap.get(a.session_id).session_date))).map(x=>`<div class="row"><span>${esc(x.detail)}</span></div>`).join('')||'<p class="empty">Nessuna presenza registrata.</p>'}</div>`:'';
 $('#report').textContent=[mode==='player'?'REPORT GIOCATORE · EBURUM':'REPORT EBURUM',player?(names.get(player)||''):null,`Periodo: ${fmt(from)} – ${fmt(to)}`,`Sessioni registrate per il giocatore: ${d.attendance.length}`,`Presenze: ${present.length}${rate===null?'':' ('+rate+'% su '+d.attendance.length+' registrazioni)'}`,`Assenze: ${absent.length}`,`Infortuni: ${injured.length}`,`Convocazioni: ${called.length}`,`Minuti giocati: ${minutes.reduce((n,r)=>n+Number(r.minutes_played||0),0)}`,`Gol dei giocatori: ${goals.length}`,`Cartellini: ${cards.length}`,`Risposte WhatsApp: ${d.attendance.filter(r=>r.notified===true).length} risposto - ${d.attendance.filter(r=>r.notified===false).length} non risposto - ${d.attendance.filter(r=>r.notified==null).length} da verificare`].filter(x=>x!=null).join('\n');
 $('#playerCharts').innerHTML=renderPlayerCharts(playerReportModel(d));$('#reportCopyStatus').textContent='';
 };
 for(const id of ['rf','rt','rp'])$('#'+id).onchange=()=>{if(id!=='rp')document.querySelectorAll('[data-report-period]').forEach(b=>b.setAttribute('aria-pressed','false'));paint()};
 document.querySelectorAll('[data-report-period]').forEach(b=>b.onclick=()=>{const period=b.dataset.reportPeriod;$('#rt').value=today();$('#rf').value=period==='month'?today().slice(0,7)+'-01':period==='all'?([...state.sessions.map(s=>s.session_date),...state.matches.map(m=>m.match_date),...(state.activities||[]).map(a=>a.activity_date)].sort()[0]||today()):recentFrom(Number(period));document.querySelectorAll('[data-report-period]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));paint()});
 $('#copyReport').onclick=()=>{if(current)copyOperationalText($('#report').textContent,$('#reportCopyStatus'),$('#reportCopyStatus').parentElement)};$('#exportReportPdf').onclick=async()=>{if(!current)return;const button=$('#exportReportPdf');button.disabled=true;try{const pdf=createPlayerReportPdf(playerReportModel(current));pdf.save(playerReportFilename(current));$('#reportCopyStatus').textContent='PDF creato. Controlla i download del dispositivo.'}catch(error){$('#reportCopyStatus').textContent='Impossibile creare il PDF: '+error.message}finally{button.disabled=!current}};paint();
};
