const db=window.supabase.createClient(window.CONFIG.supabaseUrl,window.CONFIG.supabaseAnonKey);
const app=document.querySelector('#app');
const ROLE_ORDER=['Portiere','Difensore','Centrocampista','Attaccante'];
const state={user:null,page:'dashboard',players:[],sessions:[],attendance:[],matches:[],events:[]};
const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const isAdmin=()=>state.user?.app_metadata?.role==='admin';
const fmt=d=>d?new Intl.DateTimeFormat('it-IT',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(d+'T12:00:00')):'';
const roleRank=r=>{const i=ROLE_ORDER.indexOf(r);return i<0?99:i};
const sortPlayers=a=>[...a].sort((x,y)=>roleRank(x.role)-roleRank(y.role)||(Number(x.role_order)||9999)-(Number(y.role_order)||9999)||`${x.surname} ${x.name}`.localeCompare(`${y.surname} ${y.name}`,'it'));
const activePlayers=()=>sortPlayers(state.players.filter(p=>p.active));
const badge=s=>({Presente:'b-green',Assente:'b-red',Infortunato:'b-blue'}[s]||'b-gray');
function toast(msg){const n=document.createElement('div');n.textContent=msg;Object.assign(n.style,{position:'fixed',top:'16px',left:'50%',transform:'translateX(-50%)',zIndex:100,background:'#12243a',border:'1px solid #203653',padding:'12px 16px',borderRadius:'14px'});document.body.appendChild(n);setTimeout(()=>n.remove(),2200)}
function fail(e){console.error(e);toast(e?.message||'Operazione non riuscita')}

async function boot(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});const {data:{session}}=await db.auth.getSession();state.user=session?.user||null;db.auth.onAuthStateChange((_,s)=>{state.user=s?.user||null;setTimeout(async()=>{if(state.user){const {data}=await db.auth.getUser();if(data.user)state.user=data.user;await refresh()}else renderLogin()},0)});if(state.user){const {data}=await db.auth.getUser();if(data.user)state.user=data.user;await refresh()}else renderLogin()}
function renderLogin(){trainingDraft=null;document.querySelectorAll('.modal-back').forEach(n=>n.remove());app.innerHTML=`<main class="login"><section class="login-card"><div class="brand"><img src="./icon.svg" alt="Eburum"><div><h1>Eburum</h1><small>${esc(window.CONFIG.season)} · Team Manager</small></div></div><h2>Bentornato in squadra</h2><p class="muted">Accedi con le credenziali ricevute dall’amministratore.</p><form id="loginForm"><div class="field"><label for="email">Email</label><input id="email" type="email" autocomplete="username" required></div><div class="field field-space"><label for="password">Password</label><input id="password" type="password" autocomplete="current-password" required></div><button class="primary wide field-space" id="login" type="submit">Accedi</button></form><div class="login-help">Accesso riservato. Le nuove utenze vengono create dagli amministratori.</div></section></main>`;document.querySelector('#loginForm').onsubmit=e=>{e.preventDefault();login()}}
async function login(){const button=document.querySelector('#login');if(button.disabled)return;button.disabled=true;button.textContent='Accesso…';try{const email=document.querySelector('#email').value.trim(),password=document.querySelector('#password').value;const {error}=await db.auth.signInWithPassword({email,password});if(error)throw error}catch(e){fail(e)}finally{button.disabled=false;button.textContent='Accedi'}}

async function fetchAllRows(build){const data=[];for(let offset=0;;offset+=500){const result=await build().range(offset,offset+499);if(result.error)return {data:null,error:result.error};data.push(...(result.data||[]));if((result.data||[]).length<500)return {data,error:null}}}
async function refresh(){const uid=state.user.id;const [p,s,a,m,e]=await Promise.all([
 fetchAllRows(()=>db.from('players').select('*').eq('user_id',uid).order('id')),
 fetchAllRows(()=>db.from('sessions').select('*').eq('user_id',uid).order('session_date',{ascending:false}).order('id')),
 fetchAllRows(()=>db.from('attendance').select('*').eq('user_id',uid).order('id')),
 fetchAllRows(()=>db.from('matches').select('*').eq('user_id',uid).order('match_date',{ascending:false}).order('id')),
 fetchAllRows(()=>db.from('match_events').select('*').eq('user_id',uid).order('minute').order('id'))]);
 for(const r of [p,s,a,m,e])if(r.error){fail(r.error);return false}if(state.user?.id!==uid)return false;state.players=p.data||[];state.sessions=s.data||[];state.attendance=a.data||[];state.matches=m.data||[];state.events=e.data||[];render();return true}
function navBtn(page,icon,label){return `<button data-page="${page}" class="${state.page===page?'active':''}"><b aria-hidden="true">${icon}</b><span>${label}</span></button>`}
function shell(content){return `<main class="shell"><header class="topbar"><div class="brand"><img src="./icon.svg"><div><h1>Eburum</h1><small>${esc(window.CONFIG.season)} · Team Manager</small></div></div><div class="header-actions">${isAdmin()?'<button class="ghost" id="users">Utenti</button>':''}<button class="ghost" id="logout">Esci</button></div></header>${content}</main><nav class="nav">${navBtn('dashboard','⌂','Home')}${navBtn('training','⚽','Allena')}${navBtn('players','👥','Rosa')}${navBtn('matches','🏟','Partite')}${navBtn('register','☷','Registro')}${navBtn('reports','▥','Report')}</nav>`}
function render(){const pages={dashboard,training:trainingPage,players:playersPage,matches:matchesPage,register:registerPage,reports:reportsPage};app.innerHTML=shell((pages[state.page]||pages.dashboard)());document.querySelector('#logout').onclick=()=>db.auth.signOut();const users=document.querySelector('#users');if(users)users.onclick=usersModal;document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render()});if(state.page==='players')bindPlayers();if(state.page==='training')bindTraining();if(state.page==='matches')bindMatches();if(state.page==='reports')bindReports();if(state.page==='register')bindRegister();if(state.page==='dashboard')bindDashboard()}

function dashboard(){if(!state.players.length)return `<div class="card"><h2>Importa i dati Eburum</h2><p class="muted">Il database è pronto. Inserisci il codice monouso per caricare i 30 giocatori e lo storico degli allenamenti dal file Excel.</p><div class="field"><label>Codice importazione</label><input id="claimCode" autocomplete="off" placeholder="EBURUM-...."></div><button class="primary" id="claimSeed" style="width:100%;margin-top:12px">Importa rosa e storico</button></div>`;const A=state.attendance,pres=A.filter(x=>x.status==='Presente').length,abs=A.filter(x=>x.status==='Assente').length,inf=A.filter(x=>x.status==='Infortunato').length,rit=A.filter(x=>x.delay_minutes>0).length,pct=A.length?Math.round(pres/A.length*100):0,last=state.sessions[0],lastA=last?A.filter(x=>x.session_id===last.id):[];return `<section class="hero"><div class="card"><div class="muted">Pannello squadra</div><h2>Gestisci tutto dal campo.</h2><p class="muted">Rosa, presenze, ritardi, partite e report sempre sincronizzati.</p><div class="quick"><button data-page="training">⚽<br><b>Allenamento rapido</b></button><button data-page="players">👥<br><b>Gestisci rosa</b></button><button data-page="matches">🏟<br><b>Gestisci partita</b></button></div></div><div class="card"><h3>ULTIMA SESSIONE</h3><div class="kpi">${last?fmt(last.session_date):'—'}</div><div class="muted">${last?esc(last.session_type):'Nessuna sessione'}</div>${last?`<div class="hr"></div><b>${lastA.filter(x=>x.status==='Presente').length}/${lastA.length}</b> presenti`:''}</div></section><section class="grid cards"><div class="card"><h3>GIOCATORI ATTIVI</h3><div class="kpi">${state.players.filter(p=>p.active).length}</div></div><div class="card"><h3>PRESENZA MEDIA</h3><div class="kpi">${pct}%</div></div><div class="card"><h3>ASSENZE</h3><div class="kpi">${abs}</div></div><div class="card"><h3>INFORTUNI / RITARDI</h3><div class="kpi">${inf} / ${rit}</div></div></section>`}
async function bindDashboard(){const b=document.querySelector('#claimSeed');if(!b)return;b.onclick=async()=>{try{const code=document.querySelector('#claimCode').value.trim();if(!code)throw new Error('Inserisci il codice di importazione');b.disabled=true;b.textContent='Importazione in corso...';const {data,error}=await db.rpc('claim_eburum_seed',{p_code:code});if(error)throw error;toast(`Importati ${data.players} giocatori e ${data.attendance} registrazioni`);await refresh()}catch(e){b.disabled=false;b.textContent='Importa rosa e storico';fail(e)}}}
