function registerPage(){
 const dates=[...new Set(state.sessions.map(s=>s.session_date))].sort().reverse(),latest=dates[0]||today();
 return '<div class="section-title"><div><h2>Registro</h2><div class="muted">Consulta presenze e assenze per data</div></div><span class="badge b-blue">'+state.sessions.length+' sessioni</span></div><section class="register-layout"><div class="card calendar-card"><div class="calendar-head"><button class="ghost" id="calPrev">‹</button><div><div class="row-title" id="calTitle"></div><div class="row-sub">I giorni evidenziati contengono attività</div></div><button class="ghost" id="calNext">›</button></div><div class="calendar-week"><span>Lun</span><span>Mar</span><span>Mer</span><span>Gio</span><span>Ven</span><span>Sab</span><span>Dom</span></div><div class="calendar-grid" id="calendarGrid"></div></div><div id="registerDetail" data-selected="'+latest+'"></div></section>';
}
function bindRegister(){
 const dates=[...new Set(state.sessions.map(s=>s.session_date))].sort().reverse(),activity=new Set(dates),detail=document.querySelector('#registerDetail'),grid=document.querySelector('#calendarGrid'),title=document.querySelector('#calTitle'),pm=Object.fromEntries(state.players.map(p=>[p.id,p]));
 let selected=detail.dataset.selected||today(),d0=new Date(selected+'T12:00:00'),year=d0.getFullYear(),month=d0.getMonth();
 function group(label,arr,cls){
  return '<div class="register-group"><div class="register-group-head"><span>'+label+'</span><span class="badge '+cls+'">'+arr.length+'</span></div>'+(arr.length?'<div class="register-people">'+arr.map(a=>{const p=pm[a.player_id],name=p?p.surname+' '+p.name:'Giocatore';return '<div class="person-chip"><b>'+esc(name)+'</b>'+(a.delay_minutes?'<small>Ritardo '+a.delay_minutes+' min</small>':'')+(a.note?'<small>'+esc(a.note)+'</small>':'')+'</div>'}).join('')+'</div>':'<div class="row-sub">Nessuno</div>')+'</div>';
 }
 function drawDetail(){
  const sessions=state.sessions.filter(s=>s.session_date===selected);
  if(!sessions.length){detail.innerHTML='<div class="card empty">Nessuna attività registrata il '+fmt(selected)+'.</div>';return}
  detail.innerHTML=sessions.map(s=>{const A=state.attendance.filter(a=>a.session_id===s.id),P=A.filter(a=>a.status==='Presente'),X=A.filter(a=>a.status==='Assente'),I=A.filter(a=>a.status==='Infortunato'),R=A.filter(a=>a.delay_minutes>0);return '<div class="card session-detail"><div class="session-detail-head"><div><div class="row-title">'+esc(s.session_type)+'</div><div class="row-sub">'+fmt(s.session_date)+(s.note?' · '+esc(s.note):'')+'</div></div><div class="session-summary"><span class="badge b-green">'+P.length+' P</span><span class="badge b-red">'+X.length+' A</span><span class="badge b-blue">'+I.length+' I</span>'+(R.length?'<span class="badge b-yellow">'+R.length+' R</span>':'')+'</div></div><div class="register-groups">'+group('Presenti',P,'b-green')+group('Assenti',X,'b-red')+group('Infortunati',I,'b-blue')+'</div></div>'}).join('');
 }
 function drawCalendar(){
  const first=new Date(year,month,1),last=new Date(year,month+1,0),start=(first.getDay()+6)%7;
  title.textContent=new Intl.DateTimeFormat('it-IT',{month:'long',year:'numeric'}).format(first);
  let html='';for(let i=0;i<start;i++)html+='<span class="calendar-day blank"></span>';
  for(let day=1;day<=last.getDate();day++){const key=year+'-'+String(month+1).padStart(2,'0')+'-'+String(day).padStart(2,'0');html+='<button class="calendar-day '+(activity.has(key)?'has-activity ':'')+(selected===key?'selected':'')+'" data-date="'+key+'"><span>'+day+'</span>'+(activity.has(key)?'<i></i>':'')+'</button>'}
  grid.innerHTML=html;grid.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>{selected=b.dataset.date;drawCalendar();drawDetail()});
 }
 document.querySelector('#calPrev').onclick=()=>{month--;if(month<0){month=11;year--}drawCalendar()};
 document.querySelector('#calNext').onclick=()=>{month++;if(month>11){month=0;year++}drawCalendar()};
 drawCalendar();drawDetail();
}

function matchesPage(){return `<div class="section-title"><h2>Partite</h2><button class="primary" id="addMatch">+ Partita</button></div><div class="list">${state.matches.map(m=>`<div class="row"><div><div class="row-title">Eburum – ${esc(m.opponent)}</div><div class="row-sub">${fmt(m.match_date)} · ${m.venue}${m.goals_for!=null&&m.goals_against!=null?` · ${m.goals_for}-${m.goals_against}`:''}</div></div><button data-match="${m.id}">Apri</button></div>`).join('')||'<div class="empty card">Nessuna partita.</div>'}</div>`}
function bindMatches(){document.querySelector('#addMatch').onclick=()=>matchModal();document.querySelectorAll('[data-match]').forEach(b=>b.onclick=()=>matchModal(state.matches.find(x=>x.id===b.dataset.match)))}
function matchModal(m={}){const ev=m.id?state.events.filter(e=>e.match_id===m.id):[],pm=Object.fromEntries(state.players.map(p=>[p.id,`${p.surname} ${p.name}`])),root=document.createElement('div');root.className='modal-back';root.innerHTML=`<div class="modal"><div class="modal-head"><h2>${m.id?'Gestione partita':'Nuova partita'}</h2><button id="close">✕</button></div><div class="form-grid"><div class="field"><label>Data</label><input id="md" type="date" value="${m.match_date||today()}"></div><div class="field"><label>Avversario</label><input id="mo" value="${esc(m.opponent||'')}"></div><div class="field"><label>Campo</label><select id="mv"><option ${m.venue==='Casa'?'selected':''}>Casa</option><option ${m.venue==='Trasferta'?'selected':''}>Trasferta</option></select></div><div class="field"><label>Risultato</label><div style="display:flex;gap:8px"><input id="gf" type="number" min="0" placeholder="Noi" value="${m.goals_for??''}"><input id="ga" type="number" min="0" placeholder="Loro" value="${m.goals_against??''}"></div></div></div><div class="field" style="margin-top:10px"><label>Note</label><input id="mn" value="${esc(m.note||'')}"></div><div class="toolbar" style="margin-top:14px"><button class="primary" id="save">Salva</button>${m.id?'<button id="event">+ Evento</button><button class="danger" id="delete">Elimina</button>':''}</div>${m.id?`<div class="hr"></div><h3>Eventi</h3><div class="list">${ev.map(e=>`<div class="row"><div><b>${e.minute??'—'}'</b> ${esc(e.event_type)}<div class="row-sub">${esc(pm[e.player_id]||'')} ${esc(e.detail||'')}</div></div></div>`).join('')||'<div class="muted">Nessun evento.</div>'}</div>`:''}</div>`;document.body.appendChild(root);root.querySelector('#close').onclick=()=>root.remove();root.querySelector('#save').onclick=async()=>{try{const row={user_id:state.user.id,match_date:root.querySelector('#md').value,opponent:root.querySelector('#mo').value.trim(),venue:root.querySelector('#mv').value,goals_for:root.querySelector('#gf').value===''?null:Number(root.querySelector('#gf').value),goals_against:root.querySelector('#ga').value===''?null:Number(root.querySelector('#ga').value),note:root.querySelector('#mn').value.trim()||null};if(!row.opponent)throw new Error('Inserisci avversario');const q=m.id?db.from('matches').update(row).eq('id',m.id):db.from('matches').insert(row);const {error}=await q;if(error)throw error;root.remove();await refresh()}catch(e){fail(e)}};if(m.id){root.querySelector('#delete').onclick=async()=>{if(!confirm('Eliminare partita ed eventi?'))return;const {error}=await db.from('matches').delete().eq('id',m.id);if(error)return fail(error);root.remove();await refresh()};root.querySelector('#event').onclick=()=>eventModal(m.id,root)}}
function eventModal(matchId,parent){const root=document.createElement('div');root.className='modal-back';root.style.zIndex=60;root.innerHTML=`<div class="modal"><div class="modal-head"><h2>Nuovo evento</h2><button id="close">✕</button></div><div class="form-grid"><div class="field"><label>Minuto</label><input id="min" type="number" min="0" max="130"></div><div class="field"><label>Tipo</label><select id="type"><option>Gol</option><option>Ammonizione</option><option>Espulsione</option><option>Sostituzione</option><option>Nota</option></select></div><div class="field"><label>Giocatore</label><select id="player"><option value="">—</option>${activePlayers().map(p=>`<option value="${p.id}">${esc(p.surname)} ${esc(p.name)}</option>`).join('')}</select></div><div class="field"><label>Dettaglio</label><input id="detail"></div></div><button class="primary" id="save" style="width:100%;margin-top:14px">Salva evento</button></div>`;document.body.appendChild(root);root.querySelector('#close').onclick=()=>root.remove();root.querySelector('#save').onclick=async()=>{const row={user_id:state.user.id,match_id:matchId,player_id:root.querySelector('#player').value||null,minute:Number(root.querySelector('#min').value)||0,event_type:root.querySelector('#type').value,detail:root.querySelector('#detail').value.trim()||null};const {error}=await db.from('match_events').insert(row);if(error)return fail(error);root.remove();parent.remove();await refresh();matchModal(state.matches.find(x=>x.id===matchId))}}