const db=window.supabase.createClient(window.CONFIG.supabaseUrl,window.CONFIG.supabaseAnonKey);
const app=document.querySelector('#app');
const ROLE_ORDER=['Portiere','Difensore','Centrocampista','Attaccante'];
const state={user:null,page:'dashboard',players:[],sessions:[],attendance:[],matches:[],events:[]};
const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const today=()=>new Date().toISOString().slice(0,10);
const fmt=d=>d?new Intl.DateTimeFormat('it-IT',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(d+'T12:00:00')):'';
const roleRank=r=>{const i=ROLE_ORDER.indexOf(r);return i<0?99:i};
const sortPlayers=a=>[...a].sort((x,y)=>roleRank(x.role)-roleRank(y.role)||(Number(x.role_order)||9999)-(Number(y.role_order)||9999)||`${x.surname} ${x.name}`.localeCompare(`${y.surname} ${y.name}`,'it'));
const activePlayers=()=>sortPlayers(state.players.filter(p=>p.active));
const badge=s=>({Presente:'b-green',Assente:'b-red',Infortunato:'b-blue'}[s]||'b-gray');
function toast(msg){const n=document.createElement('div');n.textContent=msg;Object.assign(n.style,{position:'fixed',top:'16px',left:'50%',transform:'translateX(-50%)',zIndex:100,background:'#12243a',border:'1px solid #203653',padding:'12px 16px',borderRadius:'14px'});document.body.appendChild(n);setTimeout(()=>n.remove(),2200)}
function fail(e){console.error(e);toast(e?.message||'Operazione non riuscita')}

async function boot(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});const {data:{session}}=await db.auth.getSession();state.user=session?.user||null;db.auth.onAuthStateChange(async(_,s)=>{state.user=s?.user||null;if(state.user)await refresh();else renderLogin()});if(state.user)await refresh();else renderLogin()}
function renderLogin(){app.innerHTML=`<main class="login"><section class="login-card"><div class="brand"><img src="./icon.svg"><div><h1>Eburum</h1><small>${esc(window.CONFIG.season)}</small></div></div><div class="field"><label>Email</label><input id="email" type="email" autocomplete="email"></div><div class="field" style="margin-top:10px"><label>Password</label><input id="password" type="password" autocomplete="current-password"></div><div class="toolbar" style="margin-top:16px"><button class="primary" id="login">Accedi</button><button class="ghost" id="signup">Crea account</button></div><p class="muted" style="font-size:12px">Il primo account riceve automaticamente rosa e storico importati dall'Excel.</p></section></main>`;document.querySelector('#login').onclick=login;document.querySelector('#signup').onclick=signup}
async function login(){try{const email=document.querySelector('#email').value.trim(),password=document.querySelector('#password').value;const {error}=await db.auth.signInWithPassword({email,password});if(error)throw error}catch(e){fail(e)}}
async function signup(){try{const email=document.querySelector('#email').value.trim(),password=document.querySelector('#password').value;if(!email)throw new Error('Inserisci la mail');if(password.length<6)throw new Error('Password di almeno 6 caratteri');const {error}=await db.auth.signUp({email,password});if(error)throw error;toast('Account creato. Se richiesto, conferma la mail.')}catch(e){fail(e)}}

async function refresh(){const uid=state.user.id;const [p,s,a,m,e]=await Promise.all([
 db.from('players').select('*').eq('user_id',uid),
 db.from('sessions').select('*').eq('user_id',uid).order('session_date',{ascending:false}),
 db.from('attendance').select('*').eq('user_id',uid),
 db.from('matches').select('*').eq('user_id',uid).order('match_date',{ascending:false}),
 db.from('match_events').select('*').eq('user_id',uid).order('minute')]);
 for(const r of [p,s,a,m,e])if(r.error)return fail(r.error);state.players=p.data||[];state.sessions=s.data||[];state.attendance=a.data||[];state.matches=m.data||[];state.events=e.data||[];render()}
function navBtn(page,icon,label){return `<button data-page="${page}" class="${state.page===page?'active':''}"><b>${icon}</b><br><span>${label}</span></button>`}
function shell(content){return `<main class="shell"><header class="topbar"><div class="brand"><img src="./icon.svg"><div><h1>Eburum</h1><small>${esc(window.CONFIG.season)} · Team Manager</small></div></div><button class="ghost" id="logout">Esci</button></header>${content}</main><nav class="nav">${navBtn('dashboard','⌂','Home')}${navBtn('training','⚽','Allenamento')}${navBtn('players','👥','Rosa')}${navBtn('matches','🏟','Partite')}${navBtn('register','☷','Registro')}${navBtn('reports','▥','Report')}</nav>`}
function render(){const pages={dashboard:dashboard(),training:trainingPage(),players:playersPage(),matches:matchesPage(),register:registerPage(),reports:reportsPage()};app.innerHTML=shell(pages[state.page]||pages.dashboard);document.querySelector('#logout').onclick=()=>db.auth.signOut();document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render()});if(state.page==='players')bindPlayers();if(state.page==='training')bindTraining();if(state.page==='matches')bindMatches();if(state.page==='reports')bindReports()}

function dashboard(){const A=state.attendance,pres=A.filter(x=>x.status==='Presente').length,abs=A.filter(x=>x.status==='Assente').length,inf=A.filter(x=>x.status==='Infortunato').length,rit=A.filter(x=>x.delay_minutes>0).length,pct=A.length?Math.round(pres/A.length*100):0,last=state.sessions[0],lastA=last?A.filter(x=>x.session_id===last.id):[];return `<section class="hero"><div class="card"><div class="muted">Pannello squadra</div><h2>Gestisci tutto dal campo.</h2><p class="muted">Rosa, presenze, ritardi, partite e report sempre sincronizzati.</p><div class="quick"><button data-page="training">⚽<br><b>Allenamento rapido</b></button><button data-page="players">👥<br><b>Gestisci rosa</b></button><button data-page="matches">🏟<br><b>Gestisci partita</b></button></div></div><div class="card"><h3>ULTIMA SESSIONE</h3><div class="kpi">${last?fmt(last.session_date):'—'}</div><div class="muted">${last?esc(last.session_type):'Nessuna sessione'}</div>${last?`<div class="hr"></div><b>${lastA.filter(x=>x.status==='Presente').length}/${lastA.length}</b> presenti`:''}</div></section><section class="grid cards"><div class="card"><h3>GIOCATORI ATTIVI</h3><div class="kpi">${state.players.filter(p=>p.active).length}</div></div><div class="card"><h3>PRESENZA MEDIA</h3><div class="kpi">${pct}%</div></div><div class="card"><h3>ASSENZE</h3><div class="kpi">${abs}</div></div><div class="card"><h3>INFORTUNI / RITARDI</h3><div class="kpi">${inf} / ${rit}</div></div></section>`}