const db=window.supabase.createClient(window.CONFIG.supabaseUrl,window.CONFIG.supabaseAnonKey);
const app=document.querySelector('#app');
const ROLE_ORDER=['Portiere','Difensore','Centrocampista','Attaccante'];
const state={user:null,page:'dashboard',players:[],sessions:[],attendance:[],matches:[],events:[]};
const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const teamOwner=()=>state.team?.owner_id||state.user.id;
const teamRole=()=>state.team?.role||(state.user?.app_metadata?.role==='admin'?'admin':'manager');
const isAdmin=()=>teamRole()==='admin';
const canManage=()=>['admin','manager'].includes(teamRole());
const canTechnical=()=>['admin','coach'].includes(teamRole());
const fmt=d=>d?new Intl.DateTimeFormat('it-IT',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(d+'T12:00:00')):'';
const roleRank=r=>{const i=ROLE_ORDER.indexOf(r);return i<0?99:i};
const sortPlayers=a=>[...a].sort((x,y)=>roleRank(x.role)-roleRank(y.role)||(Number(x.role_order)||9999)-(Number(y.role_order)||9999)||`${x.surname} ${x.name}`.localeCompare(`${y.surname} ${y.name}`,'it'));
const activePlayers=()=>sortPlayers(state.players.filter(p=>p.active));
const badge=s=>({Presente:'b-green',Assente:'b-red',Infortunato:'b-blue'}[s]||'b-gray');
function toast(msg){const n=document.createElement('div');n.textContent=msg;Object.assign(n.style,{position:'fixed',top:'16px',left:'50%',transform:'translateX(-50%)',zIndex:100,background:'#12243a',border:'1px solid #203653',padding:'12px 16px',borderRadius:'14px'});document.body.appendChild(n);setTimeout(()=>n.remove(),2200)}
function fail(e){console.error(e);toast(e?.message||'Operazione non riuscita')}

async function boot(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});const {data:{session}}=await db.auth.getSession();state.user=session?.user||null;db.auth.onAuthStateChange((_,s)=>{state.user=s?.user||null;setTimeout(async()=>{if(state.user){const {data}=await db.auth.getUser();if(data.user)state.user=data.user;await refresh()}else renderLogin()},0)});if(state.user){const {data}=await db.auth.getUser();if(data.user)state.user=data.user;await refresh()}else renderLogin()}
function renderLogin(){trainingDraft=null;state.team=null;document.querySelectorAll('.modal-back').forEach(n=>n.remove());app.innerHTML=`<main class="login"><section class="login-card"><div class="brand"><img src="./icon.svg" alt="Eburum"><div><h1>Eburum</h1><small>${esc(window.CONFIG.season)} · Team Manager</small></div></div><h2>Bentornato in squadra</h2><p class="muted">Accedi con le credenziali ricevute dall’amministratore.</p><form id="loginForm"><div class="field"><label for="email">Email</label><input id="email" type="email" autocomplete="username" required></div><div class="field field-space"><label for="password">Password</label><input id="password" type="password" autocomplete="current-password" required></div><button class="primary wide field-space" id="login" type="submit">Accedi</button></form><div class="login-help">Accesso riservato. Le nuove utenze vengono create dagli amministratori.</div></section></main>`;document.querySelector('#loginForm').onsubmit=e=>{e.preventDefault();login()}}
async function login(){const button=document.querySelector('#login');if(button.disabled)return;button.disabled=true;button.textContent='Accesso…';try{const email=document.querySelector('#email').value.trim(),password=document.querySelector('#password').value;const {error}=await db.auth.signInWithPassword({email,password});if(error)throw error}catch(e){fail(e)}finally{button.disabled=false;button.textContent='Accedi'}}

async function fetchAllRows(build){const data=[];for(let offset=0;;offset+=500){const result=await build().range(offset,offset+499);if(result.error)return {data:null,error:result.error};data.push(...(result.data||[]));if((result.data||[]).length<500)return {data,error:null}}}
async function refresh(){
 const actor=state.user?.id;if(!actor)return false;
 const context=await db.rpc('team_context');if(state.user?.id!==actor)return false;
 if(context.error||!context.data){document.querySelectorAll('.modal-back').forEach(n=>n.remove());state.team=null;trainingDraft=null;showTeamLoadError(context.error||new Error('Utenza non associata a una squadra'));return false}
 if(state.loadedActor!==actor||state.team?.owner_id!==context.data.owner_id||state.team?.role!==context.data.role){document.querySelectorAll('.modal-back').forEach(n=>n.remove());trainingDraft=null;app.innerHTML='<main class="shell"><div class="card" role="status">Caricamento squadra…</div></main>'}
 state.team=context.data;state.loadedActor=actor;const uid=teamOwner();
 const tables=['players','sessions','attendance','matches','match_events','activities','activity_roster','player_administration','activity_technical'];
 const results=await Promise.all(tables.map(table=>fetchAllRows(()=>db.from(table).select('*').eq('user_id',uid).order(table==='player_administration'?'player_id':table==='activity_technical'?'activity_id':'id'))));
 if(state.user?.id!==actor)return false;for(const r of results)if(r.error){showTeamLoadError(r.error);return false}
 for(let i=0;i<tables.length;i++)state[({match_events:'events',activity_roster:'roster',player_administration:'administration',activity_technical:'technical'})[tables[i]]||tables[i]]=results[i].data||[];
 state.sessions.sort((a,b)=>b.session_date.localeCompare(a.session_date));state.matches.sort((a,b)=>b.match_date.localeCompare(a.match_date));render();return true
}
function showTeamLoadError(error){app.innerHTML=`<main class="shell"><div class="card"><h2>Squadra non caricata</h2><p>${esc(error.message||'Connessione non disponibile')}</p><div class="toolbar"><button id="retryTeam">Riprova</button><button id="exitTeam">Esci</button></div></div></main>`;document.querySelector('#retryTeam').onclick=()=>refresh();document.querySelector('#exitTeam').onclick=()=>db.auth.signOut()}
function navBtn(page,icon,label){const paths={dashboard:'<path d="m3 10 9-7 9 7v10H3z"/><path d="M9 20v-7h6v7"/>',training:'<circle cx="12" cy="12" r="9"/><path d="m12 7 5 4-2 6H9l-2-6zM12 3v4m9 5-4-1m1 8-3-2m-9 2 3-2m-6-5 4-1"/>',players:'<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3m1-16a3 3 0 0 1 0 6m2 4a5 5 0 0 1 3 5v1"/>',matches:'<path d="M4 5h16v15H4zM8 5V3m8 2V3M4 10h16"/><path d="M8 14h2m4 0h2m-8 3h2m4 0h2"/>',register:'<path d="M8 5h12v16H4V5h4m0-2h8v4H8zM8 12h8m-8 4h8"/>',reports:'<path d="M4 21V3m0 18h17M8 17v-5m5 5V8m5 9V5"/>'};return `<button data-page="${page}" class="${state.page===page?'active':''}" ${state.page===page?'aria-current="page"':''}><b aria-hidden="true"><svg viewBox="0 0 24 24">${paths[page]}</svg></b><span>${label}</span></button>`}
function shell(content){return `<main class="shell"><header class="topbar"><div class="brand"><img src="./icon.svg"><div><h1>Eburum</h1><small>${esc(window.CONFIG.season)} · Team Manager</small></div></div><div class="header-actions">${isAdmin()?'<button class="ghost" id="users">Utenti</button>':''}<button class="ghost" id="logout">Esci</button></div></header>${content}</main><nav class="nav">${navBtn('dashboard','⌂','Home')}${navBtn('training','⚽','Allena')}${navBtn('players','👥','Rosa')}${navBtn('matches','🏟','Partite')}${navBtn('register','☷','Registro')}${navBtn('reports','▥','Report')}</nav>`}
function render(){const pages={dashboard,training:trainingPage,players:playersPage,matches:matchesPage,register:registerPage,reports:reportsPage,agenda:agendaPage,more:morePage};app.innerHTML=shell((pages[state.page]||pages.dashboard)());document.querySelector('#logout').onclick=()=>db.auth.signOut();const users=document.querySelector('#users');if(users)users.onclick=usersModal;document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render()});if(state.page==='players')bindPlayers();if(state.page==='training')bindTraining();if(state.page==='matches')bindMatches();if(state.page==='reports')bindReports();if(state.page==='register')bindRegister();if(state.page==='dashboard')bindDashboard();if(state.page==='agenda')bindAgenda();if(state.page==='more')bindMore();bindTeamLinks()}

function dashboard(){if(!state.players.length)return `<div class="card"><h2>Importa i dati Eburum</h2><p class="muted">Il database è pronto. Inserisci il codice monouso per caricare i 30 giocatori e lo storico degli allenamenti dal file Excel.</p><div class="field"><label>Codice importazione</label><input id="claimCode" autocomplete="off" placeholder="EBURUM-...."></div><button class="primary" id="claimSeed" style="width:100%;margin-top:12px">Importa rosa e storico</button></div>`;const A=state.attendance,pres=A.filter(x=>x.status==='Presente').length,abs=A.filter(x=>x.status==='Assente').length,inf=A.filter(x=>x.status==='Infortunato').length,rit=A.filter(x=>x.delay_minutes>0).length,pct=A.length?Math.round(pres/A.length*100):0,last=state.sessions[0],lastA=last?A.filter(x=>x.session_id===last.id):[];return `<section class="hero"><div class="card"><div class="muted">Pannello squadra</div><h2>Gestisci tutto dal campo.</h2><p class="muted">Rosa, presenze, partite e report sempre sincronizzati.</p><div class="quick"><button data-page="training">⚽<br><b>Allenamento rapido</b></button><button data-page="players">👥<br><b>Gestisci rosa</b></button><button data-page="matches">🏟<br><b>Gestisci partita</b></button></div></div><div class="card"><h3>ULTIMA SESSIONE</h3><div class="kpi">${last?fmt(last.session_date):'—'}</div><div class="muted">${last?esc(last.session_type):'Nessuna sessione'}</div>${last?`<div class="hr"></div><b>${lastA.filter(x=>x.status==='Presente').length}/${lastA.length}</b> presenti`:''}</div></section><section class="grid cards"><div class="card"><h3>GIOCATORI ATTIVI</h3><div class="kpi">${state.players.filter(p=>p.active).length}</div></div><div class="card"><h3>PRESENZA MEDIA</h3><div class="kpi">${pct}%</div></div><div class="card"><h3>ASSENZE</h3><div class="kpi">${abs}</div></div><div class="card"><h3>INFORTUNI</h3><div class="kpi">${inf}</div></div></section>`}
async function bindDashboard(){const b=document.querySelector('#claimSeed');if(!b)return;b.onclick=async()=>{try{const code=document.querySelector('#claimCode').value.trim();if(!code)throw new Error('Inserisci il codice di importazione');b.disabled=true;b.textContent='Importazione in corso...';const {data,error}=await db.rpc('claim_eburum_seed',{p_code:code});if(error)throw error;toast(`Importati ${data.players} giocatori e ${data.attendance} registrazioni`);await refresh()}catch(e){b.disabled=false;b.textContent='Importa rosa e storico';fail(e)}}}
