function reportsPage(){
 const opts=sortPlayers(state.players).map(p=>'<option value="'+p.id+'">'+esc(p.surname)+' '+esc(p.name)+'</option>').join('');
 return '<div class="section-title"><div><h2>Report</h2><div class="muted">Riepilogo società o scheda del singolo giocatore</div></div><button class="primary" id="copyReport">Copia testo</button></div><div class="report-tabs"><button class="active" data-report-tab="team">Squadra</button><button data-report-tab="player">Giocatore</button></div><div class="card"><div class="form-grid"><div class="field"><label>Dal</label><input id="rf" type="date" value="'+new Date(new Date().setDate(1)).toISOString().slice(0,10)+'"></div><div class="field"><label>Al</label><input id="rt" type="date" value="'+today()+'"></div></div><div id="playerPicker" class="field" style="margin-top:12px;display:none"><label>Giocatore</label><select id="rp">'+opts+'</select></div><div id="reportStats" class="player-kpis" style="margin-top:14px"></div><div id="report" class="report" style="margin-top:14px"></div><div id="playerHistory" class="player-history"></div></div>';
}
function bindReports(){
 let mode='team';const report=document.querySelector('#report'),stats=document.querySelector('#reportStats'),history=document.querySelector('#playerHistory'),picker=document.querySelector('#playerPicker');
 function dataRange(){const from=document.querySelector('#rf').value,to=document.querySelector('#rt').value,s=state.sessions.filter(x=>x.session_date>=from&&x.session_date<=to),ids=new Set(s.map(x=>x.id));return {from,to,s,A:state.attendance.filter(a=>ids.has(a.session_id))}}
 function paint(){
  const d=dataRange();history.innerHTML='';
  if(mode==='team'){const pres=d.A.filter(a=>a.status==='Presente').length,abs=d.A.filter(a=>a.status==='Assente').length,inf=d.A.filter(a=>a.status==='Infortunato').length,rit=d.A.filter(a=>a.delay_minutes>0),mins=rit.reduce((n,a)=>n+a.delay_minutes,0);stats.innerHTML='<div><b>'+d.s.length+'</b><span>Sessioni</span></div><div><b>'+pres+'</b><span>Presenze</span></div><div><b>'+abs+'</b><span>Assenze</span></div><div><b>'+rit.length+'</b><span>Ritardi</span></div>';report.textContent='REPORT EBURUM\nPeriodo: '+fmt(d.from)+' - '+fmt(d.to)+'\n\nSessioni: '+d.s.length+'\nPresenze: '+pres+'\nAssenze: '+abs+'\nInfortuni: '+inf+'\nRitardi: '+rit.length+'\nMinuti totali di ritardo: '+mins;return report.textContent}
  const id=document.querySelector('#rp').value,p=state.players.find(x=>x.id===id),A=d.A.filter(a=>a.player_id===id),pres=A.filter(a=>a.status==='Presente').length,abs=A.filter(a=>a.status==='Assente').length,inf=A.filter(a=>a.status==='Infortunato').length,rit=A.filter(a=>a.delay_minutes>0),mins=rit.reduce((n,a)=>n+a.delay_minutes,0),pct=A.length?Math.round(pres/A.length*100):0,sm=Object.fromEntries(d.s.map(s=>[s.id,s]));
  stats.innerHTML='<div><b>'+pct+'%</b><span>Presenza</span></div><div><b>'+pres+'</b><span>Presenze</span></div><div><b>'+abs+'</b><span>Assenze</span></div><div><b>'+inf+'</b><span>Infortuni</span></div>';
  report.textContent='REPORT GIOCATORE - EBURUM\n'+(p?p.surname+' '+p.name:'')+'\nPeriodo: '+fmt(d.from)+' - '+fmt(d.to)+'\n\nSessioni considerate: '+A.length+'\nPresenze: '+pres+' ('+pct+'%)\nAssenze: '+abs+'\nInfortuni: '+inf+'\nRitardi: '+rit.length+'\nMinuti totali di ritardo: '+mins;
  history.innerHTML='<h3>Storico nel periodo</h3><div class="list">'+[...A].sort((a,b)=>(sm[b.session_id]?.session_date||'').localeCompare(sm[a.session_id]?.session_date||'')).map(a=>{const s=sm[a.session_id]||{};return '<div class="row compact-row"><div><div class="row-title">'+fmt(s.session_date)+' · '+esc(s.session_type||'')+'</div><div class="row-sub">'+(a.delay_minutes?'Ritardo '+a.delay_minutes+' min · ':'')+(a.note?esc(a.note):'Nessuna nota')+'</div></div><span class="badge '+badge(a.status)+'">'+a.status+'</span></div>'}).join('')+'</div>';
  return report.textContent;
 }
 document.querySelectorAll('[data-report-tab]').forEach(b=>b.onclick=()=>{mode=b.dataset.reportTab;document.querySelectorAll('[data-report-tab]').forEach(x=>x.classList.toggle('active',x===b));picker.style.display=mode==='player'?'grid':'none';paint()});
 document.querySelector('#rf').onchange=paint;document.querySelector('#rt').onchange=paint;document.querySelector('#rp').onchange=paint;paint();
 document.querySelector('#copyReport').onclick=async()=>{await navigator.clipboard.writeText(paint());toast('Report copiato')};
}
